

#
#
# these are comments
#
#

ssh {
	sequence: 6500,3000,2120,1480,515,447,319;
	timeout: 25;
	service: ssh;
	port: 666;
	command_start: /sbin/iptables -I input_ssh_new 1 --source %s -m conntrack --ctstate NEW -j ACCEPT;
	command_timeout: 10;
	command_end: /usr/sbin/input_ssh_remove %s;
	type: command-trigger;
}

http {
	sequence: 10001,10002,1510,9959,10003,319,17,4905;
	timeout: 25;
	service: http;
	port: 80;
	command_start: /sbin/iptables -I input_http_new 1 --source %s -m conntrack --ctstate NEW -j ACCEPT;
	command_timeout: 10;
	command_end: /usr/sbin/input_http_remove %s;
	type: command-trigger;
}

cleanup {
	sequence: 1412,3999,8080,420,666,17,3139;
	timeout: 10;
	type: cleanup;
}
